import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, MapPin, ShieldCheck, Users } from "lucide-react";
import { leaders, priorities, resources } from "@/content/site";
export default function Home() { return <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">Allied Peoples' Movement</p><h1>Nigeria First.<br /><span>People always.</span></h1><p className="hero-intro">A political movement committed to accountable leadership, equal opportunity and a secure, prosperous Nigeria.</p><div className="hero-actions"><a className="button" href="https://members-register.apm.org.ng/">Become a member <ArrowRight size={18} /></a><Link className="text-link" href="/about">About APM</Link></div></div><div className="hero-mark" aria-label="APM party colours and emblem"><span className="flag-green" /><span className="flag-white"><Image src="/apm-logo.jpg" alt="APM emblem" width={240} height={240} priority /></span><span className="flag-blue" /></div><div className="hero-facts"><span>One nation</span><span>36 states + FCT</span><span>Grassroots powered</span></div></section>
  <section className="quick-resources"><p className="section-label">Quick access</p><div className="quick-grid"><Link href="/resources"><BookOpen /><span><strong>Party documents</strong><small>Manifesto and Constitution</small></span><ArrowRight /></Link><Link href="/leadership"><Users /><span><strong>Leadership</strong><small>National Working Committee</small></span><ArrowRight /></Link><Link href="/contact"><MapPin /><span><strong>Find APM</strong><small>Secretariat and contacts</small></span><ArrowRight /></Link><a href="https://members-register.apm.org.ng/"><ShieldCheck /><span><strong>Membership</strong><small>Register or access your account</small></span><ArrowRight /></a></div></section>
  <section className="purpose"><div><p className="section-label">Our purpose</p><h2>Leadership that answers to the people.</h2></div><div><p>APM exists to strengthen democratic institutions, protect every citizen's dignity and build a country where opportunity is not determined by origin, faith, gender or circumstance.</p><Link className="text-link" href="/about">Learn about APM <ArrowRight size={17} /></Link></div></section>
  <section className="priorities"><div className="section-heading"><p className="section-label">What we stand for</p><h2>A practical agenda for national renewal</h2><p>Six commitments guide our approach to government and public service.</p></div><div className="priority-grid">{priorities.map((item) => <article key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div><Link className="section-link" href="/policies">Explore policy priorities <ArrowRight /></Link></section>
  <section className="leadership"><div className="section-heading light"><p className="section-label">National leadership</p><h2>Service with responsibility</h2><p>Verified national officers currently listed by the Independent National Electoral Commission.</p></div><div className="leader-grid">{leaders.map((leader, index) => <article className={index === 0 ? "leader-featured" : ""} key={leader.name}><span>{leader.initials}</span><div><p>{leader.role}</p><h3>{leader.name}</h3></div></article>)}</div><Link className="section-link light" href="/leadership">View leadership <ArrowRight /></Link></section>
  <section className="resource-preview"><div className="section-heading"><p className="section-label">Party resources</p><h2>Read our founding documents</h2></div>{resources.map((resource) => <article key={resource.title}><span>{resource.type}</span><div><h3>{resource.title}</h3><p>{resource.description}</p></div><a className="button button-secondary" href={resource.href}>Read document <ArrowRight size={17} /></a></article>)}</section>
  <section className="public-updates"><div><p className="section-label">News and events</p><h2>Verified updates only.</h2><p>News and events will appear after editorial approval. Sample template articles have been removed from the redesign.</p></div><div><Link className="button button-secondary" href="/news">Visit the newsroom</Link><Link className="button button-secondary" href="/events">View events</Link></div></section>
  <section className="join-band"><p className="section-label">Take part</p><h2>Nigeria's future belongs to everyone.</h2><p>Join citizens across the country working for integrity, service and opportunity.</p><Link className="button button-light" href="/get-involved">Explore ways to participate <ArrowRight size={18} /></Link></section>
</main>; }
