import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, MapPin, ShieldCheck, Users } from "lucide-react";
import { leaders, priorities, resources } from "@/content/site";
export default function Home() { return <main>
  <section className="hero hero-photo"><Image src="/images/apm/event-03.jpg" alt="APM officials holding party nomination forms at a public party activity" fill sizes="100vw" priority /><div className="hero-overlay" /><div className="hero-copy"><p className="eyebrow">Allied Peoples' Movement</p><h1>Nigeria First.<br /><span>People always.</span></h1><p className="hero-intro">A political movement committed to accountable leadership, equal opportunity and a secure, prosperous Nigeria.</p><div className="hero-actions"><Link className="button" href="/membership/register">Become a member <ArrowRight size={18} /></Link><Link className="text-link" href="/about">About APM</Link></div></div><div className="hero-credit">Official APM public gallery</div><div className="hero-facts"><span>One nation</span><span>36 states + FCT</span><span>Grassroots powered</span></div></section>
  <section className="quick-resources"><p className="section-label">Quick access</p><div className="quick-grid"><Link href="/resources"><BookOpen /><span><strong>Party documents</strong><small>Manifesto and Constitution</small></span><ArrowRight /></Link><Link href="/leadership"><Users /><span><strong>Leadership</strong><small>National Working Committee</small></span><ArrowRight /></Link><Link href="/contact"><MapPin /><span><strong>Find APM</strong><small>Secretariat and contacts</small></span><ArrowRight /></Link><Link href="/membership/login"><ShieldCheck /><span><strong>Membership</strong><small>Register or access your account</small></span><ArrowRight /></Link></div></section>
  <section className="purpose"><div><p className="section-label">Our purpose</p><h2>Leadership that answers to the people.</h2></div><div><p>APM exists to strengthen democratic institutions, protect every citizen's dignity and build a country where opportunity is not determined by origin, faith, gender or circumstance.</p><Link className="text-link" href="/about">Learn about APM <ArrowRight size={17} /></Link></div></section>
  <section className="priorities"><div className="section-heading"><p className="section-label">What we stand for</p><h2>A practical agenda for national renewal</h2><p>Six commitments guide our approach to government and public service.</p></div><div className="priority-grid">{priorities.map((item) => <article key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div><Link className="section-link" href="/policies">Explore policy priorities <ArrowRight /></Link></section>
  <section className="leadership"><div className="section-heading light"><p className="section-label">National leadership</p><h2>Service with responsibility</h2><p>Verified national officers currently listed by the Independent National Electoral Commission.</p></div><div className="leader-grid">{leaders.map((leader, index) => <article className={index === 0 ? "leader-featured" : ""} key={leader.name}>{"image" in leader ? <Image src={leader.image} alt={`Portrait of ${leader.name}, ${leader.role}`} width={150} height={150} /> : <span>{leader.initials}</span>}<div><p>{leader.role}</p><h3>{leader.name}</h3></div></article>)}</div><Link className="section-link light" href="/leadership">View leadership <ArrowRight /></Link></section>
  <section className="official-gallery"><div className="section-heading"><p className="section-label">APM in public life</p><h2>Official photographs from party activities</h2><p>Images published through APM&apos;s official public website.</p></div><div className="official-gallery-grid"><figure className="gallery-wide"><Image src="/images/apm/party-meeting.jpg" alt="APM officials meeting around a conference table" fill sizes="(max-width: 800px) 100vw, 58vw" /><figcaption>Party officials during an APM meeting.</figcaption></figure><figure><Image src="/images/apm/nomination-presentation.jpg" alt="APM officials presenting a party nomination form" fill sizes="(max-width: 800px) 100vw, 42vw" /><figcaption>Officials at an APM nomination-form presentation.</figcaption></figure><figure><Image src="/images/apm/event-05.jpeg" alt="Party leaders and supporters at a public APM event" fill sizes="(max-width: 800px) 100vw, 42vw" /><figcaption>Party leaders and supporters at a public event.</figcaption></figure></div><p className="gallery-source">Source: <a href="https://apm.org.ng/">APM official website</a>.</p></section>
  <section className="resource-preview"><div className="section-heading"><p className="section-label">Party resources</p><h2>Read our founding documents</h2></div>{resources.map((resource) => <article key={resource.title}><span>{resource.type}</span><div><h3>{resource.title}</h3><p>{resource.description}</p></div><a className="button button-secondary" href={resource.href}>Read document <ArrowRight size={17} /></a></article>)}</section>
  <section className="public-updates"><div><p className="section-label">News and events</p><h2>Verified updates only.</h2><p>News and events will appear after editorial approval. Sample template articles have been removed from the redesign.</p></div><div><Link className="button button-secondary" href="/news">Visit the newsroom</Link><Link className="button button-secondary" href="/events">View events</Link></div></section>
  <section className="join-band"><p className="section-label">Take part</p><h2>Nigeria's future belongs to everyone.</h2><p>Join citizens across the country working for integrity, service and opportunity.</p><Link className="button button-light" href="/get-involved">Explore ways to participate <ArrowRight size={18} /></Link></section>
</main>; }
