"use client";
import { SiteLink as Link } from "@/components/site-link";
import { FormEvent, useEffect, useState } from "react";

function Notice({ message, error = false }: { message: string; error?: boolean }) { return message ? <div className={error ? "form-notice error" : "form-notice"} role="status">{message}</div> : null; }
async function send(url: string, body: unknown, method = "POST") { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const type = response.headers.get("content-type") ?? ""; const data = type.includes("application/json") ? await response.json() : { error: response.ok ? "Unexpected server response." : "The membership service is temporarily unavailable." }; if (!response.ok) throw new Error(data.error ?? "Please try again."); return data; }

type LocationOption = { id: string; name: string };
function LocationFields({ defaults = {} }: { defaults?: { state?: string; lga?: string; ward?: string } }) {
  const [states, setStates] = useState<LocationOption[]>([]), [lgas, setLgas] = useState<LocationOption[]>([]), [wards, setWards] = useState<LocationOption[]>([]);
  const [stateId, setStateId] = useState(""), [lgaId, setLgaId] = useState("");
  useEffect(() => { fetch("/api/locations?level=state").then((response) => response.json()).then((data) => setStates(data.items ?? [])); }, []);
  useEffect(() => { if (!stateId) { setLgas([]); setWards([]); return; } fetch(`/api/locations?level=lga&parent=${encodeURIComponent(stateId)}`).then((response) => response.json()).then((data) => setLgas(data.items ?? [])); }, [stateId]);
  useEffect(() => { if (!lgaId) { setWards([]); return; } fetch(`/api/locations?level=ward&parent=${encodeURIComponent(lgaId)}`).then((response) => response.json()).then((data) => setWards(data.items ?? [])); }, [lgaId]);
  return <><label>State<select name="state" required defaultValue={defaults.state ?? ""} onChange={(event) => { const option = states.find((item) => item.name === event.target.value); setStateId(option?.id ?? ""); setLgaId(""); }}><option value="">Select state</option>{states.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>LGA / Area Council<select name="lga" required defaultValue={defaults.lga ?? ""} disabled={!stateId} onChange={(event) => { const option = lgas.find((item) => item.name === event.target.value); setLgaId(option?.id ?? ""); }}><option value="">Select LGA</option>{lgas.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>Ward / Registration Area<select name="ward" required defaultValue={defaults.ward ?? ""} disabled={!lgaId}><option value="">Select ward</option>{wards.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label></>;
}

export function RegistrationForm() {
  const [step, setStep] = useState(1), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(false), [email, setEmail] = useState(""), [devCode, setDevCode] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try { const result = await send("/api/membership/register", Object.fromEntries(form.entries())); setEmail(String(form.get("email"))); setDevCode(result.developmentCode ?? ""); setStep(2); } catch (e) { setError(true); setMessage(e instanceof Error ? e.message : "Please try again."); } finally { setBusy(false); } }
  if (step === 2) return <div className="member-form"><div className="form-progress"><span className="complete">1</span><i /><span className="active">2</span></div><h2>Check your email</h2><p>Enter the six-digit code sent to <strong>{email}</strong>.</p>{devCode && <Notice message={`Local test code: ${devCode}`} />}<VerificationForm email={email} /></div>;
  return <form className="member-form" onSubmit={submit}><div className="form-progress"><span className="active">1</span><i /><span>2</span></div><h2>Your membership details</h2><p>Fields marked required are needed to create your application.</p><div className="form-grid"><label>First name<input name="firstName" required autoComplete="given-name" /></label><label>Middle name<input name="middleName" autoComplete="additional-name" /></label><label>Last name<input name="lastName" required autoComplete="family-name" /></label><label>Email address<input name="email" type="email" required autoComplete="email" /></label><label>Phone number<input name="phone" type="tel" required autoComplete="tel" /></label><LocationFields /></div><label className="check-row"><input name="consent" type="checkbox" value="true" required /> <span>I confirm these details are mine and agree to their use for membership administration under the <Link href="/privacy">privacy notice</Link>.</span></label><Notice message={message} error={error} /><button className="button" disabled={busy}>{busy ? "Creating application..." : "Continue to email verification"}</button></form>;
}

export function VerificationForm({ email: initialEmail = "" }: { email?: string }) {
  const [email, setEmail] = useState(initialEmail), [code, setCode] = useState(""), [message, setMessage] = useState(""), [reference, setReference] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); try { const result = await send("/api/membership/verify", { email, code }); setReference(result.reference); } catch (e) { setMessage(e instanceof Error ? e.message : "Please try again."); } }
  if (reference) return <div className="success-panel" role="status"><h2>Email verified</h2><p>Your membership application is now awaiting APM review.</p><dl><dt>Membership reference</dt><dd>{reference}</dd></dl><Link className="button" href="/membership/login">Access member dashboard</Link></div>;
  return <form className="compact-form" onSubmit={submit}><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Six-digit code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(e) => setCode(e.target.value)} required /></label><Notice message={message} error /><button className="button">Verify email</button></form>;
}

export function LoginForm() {
  const [step, setStep] = useState(1), [email, setEmail] = useState(""), [code, setCode] = useState(""), [message, setMessage] = useState(""), [devCode, setDevCode] = useState("");
  async function requestCode(event: FormEvent) { event.preventDefault(); setMessage(""); try { const result = await send("/api/membership/login/request", { email }); setDevCode(result.developmentCode ?? ""); setStep(2); } catch (e) { setMessage(e instanceof Error ? e.message : "Please try again."); } }
  async function verify(event: FormEvent) { event.preventDefault(); setMessage(""); try { await send("/api/membership/login/verify", { email, code }); window.location.assign("/member/dashboard"); } catch (e) { setMessage(e instanceof Error ? e.message : "Please try again."); } }
  return <form className="member-form compact" onSubmit={step === 1 ? requestCode : verify}><h2>{step === 1 ? "Access your account" : "Enter your access code"}</h2><p>{step === 1 ? "We will send a one-time code to your verified email. No password is required." : `Use the code sent to ${email}.`}</p><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} disabled={step === 2} required /></label>{step === 2 && <label>Six-digit code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(e) => setCode(e.target.value)} required autoFocus /></label>}{devCode && <Notice message={`Local test code: ${devCode}`} />}<Notice message={message} error /><button className="button">{step === 1 ? "Send access code" : "Open dashboard"}</button><p className="form-footnote">New to APM? <Link href="/membership/register">Start a membership application</Link>.</p></form>;
}

export function ProfileForm({ member }: { member: Record<string, unknown> }) {
  const [message, setMessage] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await send("/api/membership/profile", Object.fromEntries(form.entries()), "PATCH"); setMessage("Profile updated."); } catch (e) { setMessage(e instanceof Error ? e.message : "Please try again."); } }
  return <form className="member-form compact" onSubmit={submit}><label>Phone number<input name="phone" defaultValue={String(member.phone ?? "")} required /></label><LocationFields defaults={{ state: String(member.state_code ?? ""), lga: String(member.lga_name ?? ""), ward: String(member.ward_name ?? "") }} /><Notice message={message} /><button className="button">Save profile</button></form>;
}

export function LogoutButton() { async function logout() { await fetch("/api/membership/logout", { method: "POST" }); window.location.assign("/"); } return <button className="button button-secondary" onClick={logout}>Sign out</button>; }
