"use client";
import { FormEvent, useState } from "react";
type Option = { id: string; name: string; code?: string };
export function PollingAgentForm({ elections, states }: { elections: Option[]; states: Option[] }) {
  const [lgas, setLgas] = useState<Option[]>([]), [wards, setWards] = useState<Option[]>([]), [units, setUnits] = useState<Option[]>([]), [message, setMessage] = useState(""), [reference, setReference] = useState("");
  async function load(parentId: string, type: string, setter: (items: Option[]) => void) { setter([]); if (!parentId) return; const response = await fetch(`/api/polling-agent/options?parentId=${encodeURIComponent(parentId)}&type=${type}`); const data = await response.json(); setter(data.items ?? []); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/polling-agent/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const data = await response.json(); if (!response.ok) setMessage(data.error); else setReference(data.reference); }
  if (!elections.length || !states.length) return <div className="availability-panel"><h2>Applications are not open yet</h2><p>The application workflow is ready, but it will remain closed until APM approves an election and the verified INEC directory is imported. No sample locations are shown.</p></div>;
  if (reference) return <div className="success-panel"><h2>Application submitted</h2><p>Keep this reference for your records.</p><dl><dt>Application reference</dt><dd>{reference}</dd></dl></div>;
  return <form className="member-form" onSubmit={submit}><h2>Polling-agent application</h2><label>Election<select name="electionId" required defaultValue=""><option value="" disabled>Select an open election</option>{elections.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="form-grid"><label>State<select required defaultValue="" onChange={(e) => { setWards([]); setUnits([]); load(e.target.value, "lga", setLgas); }}><option value="" disabled>Select state</option>{states.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>LGA / Area Council<select required defaultValue="" onChange={(e) => { setUnits([]); load(e.target.value, "ward", setWards); }}><option value="" disabled>Select LGA</option>{lgas.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Ward / Registration Area<select required defaultValue="" onChange={(e) => load(e.target.value, "polling_unit", setUnits)}><option value="" disabled>Select ward</option>{wards.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Polling unit<select name="pollingUnitId" required defaultValue=""><option value="" disabled>Select polling unit</option>{units.map(x => <option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></label></div><label>Relevant experience<textarea name="experience" rows={5} maxLength={1200} /></label><label className="check-row"><input name="availabilityConfirmed" type="checkbox" value="true" required /><span>I confirm that I am available for the selected election and that these details are accurate.</span></label>{message && <div className="form-notice error">{message}</div>}<button className="button">Review and submit</button></form>;
}
