import Link from "next/link";
import { redirect } from "next/navigation";
import { LogoutButton } from "@/components/membership-forms";
import { getCurrentMember, getD1, publicStatus } from "@/lib/member-auth";
export const dynamic = "force-dynamic";
export default async function DashboardPage() {
  const member = await getCurrentMember(); if (!member) redirect("/membership/login");
  const applications = await getD1().prepare(`SELECT a.application_reference, a.status, a.submitted_at, e.name election_name, p.name polling_unit_name, p.code polling_unit_code FROM polling_agent_applications a JOIN elections e ON e.id = a.election_id JOIN inec_locations p ON p.id = a.polling_unit_id WHERE a.member_id = ? ORDER BY a.submitted_at DESC`).bind(member.id).all<Record<string, unknown>>();
  return <main className="dashboard-shell"><header className="dashboard-heading"><div><p className="eyebrow">Member dashboard</p><h1>Hello, {String(member.first_name)}.</h1><p>Reference: <strong>{String(member.membership_reference)}</strong></p></div><LogoutButton /></header><section className="status-strip"><div><span>Membership status</span><strong>{publicStatus(String(member.status))}</strong></div><div><span>Email</span><strong>{member.email_verified_at ? "Verified" : "Verification required"}</strong></div><div><span>Polling-agent eligibility</span><strong>{member.status === "approved" ? "Eligible to apply" : "Approval required"}</strong></div></section><div className="dashboard-grid"><section><div className="panel-heading"><h2>Your profile</h2><Link href="/member/profile">Edit profile</Link></div><dl className="profile-list"><dt>Name</dt><dd>{[member.first_name, member.middle_name, member.last_name].filter(Boolean).join(" ")}</dd><dt>Email</dt><dd>{String(member.email)}</dd><dt>Phone</dt><dd>{String(member.phone)}</dd><dt>Ward</dt><dd>{String(member.ward_name ?? "Not provided")}</dd></dl></section><section><div className="panel-heading"><h2>Polling-agent applications</h2>{member.status === "approved" && <Link href="/polling-agent">Start application</Link>}</div>{applications.results.length ? <div className="application-list">{applications.results.map((item) => <article key={String(item.application_reference)}><strong>{String(item.election_name)}</strong><span>{String(item.application_reference)}</span><span>{String(item.polling_unit_code)} - {String(item.polling_unit_name)}</span><b>{String(item.status).replaceAll("_", " ")}</b></article>)}</div> : <div className="dashboard-empty"><p>No polling-agent applications yet.</p><span>Applications will appear here with their current decision status.</span></div>}</section></div></main>;
}
